### ISSUE TITLE
Links no longer working

### ISSUE THREAD

**Issue by dotmick** [JUL1EN094/JUL1EN094-xbmc-addons#15]
Hi,

Everything was working great a week ago but France TV might have change their streaming architecture: the links _http://live.francetv.fr/simulcast/France_2/hls_v1/index.m3u8_ are no longer working (error 403).

**Comment by X-ardion** [comment]
How can we solve the problem?

**Comment by dotmick** [comment]
Well, that's not my addon so I don't know the mechanism as well as the process you've followed to find links. I don't know if you guys are still maintaining the addon actually.

**Comment by k3rotan** [comment]
Looks like Francetv pluzz doesn't allowed anymore streaming.

**Comment by X-ardion** [comment]
Working now !!

**Comment by Meseira** [comment]
I confirm that streaming is working now. This problem is strange and, up to me, maybe related to broadcasting rights during the Olympics considering the dates of the start and end of the problem...

**Comment by awiouy** [comment]
This issue is reoccurring: the addon fails for the same reason as above. Pluzz from a web browser works fine. Any idea how to fix @JUL1EN094 ?

**Comment by JUL1EN094** [comment]
Please try last commit : https://github.com/JUL1EN094/JUL1EN094-xbmc-addons/commit/297c5ad5f144caf8eea916e33aee6af4ac371276

If you could gimme a feedback ?

**Comment by awiouy** [comment]
Au poil! It works! Thanks much!

**Comment by Meseira** [comment]
Yes, it morks again! Thank you JUL1EN094 :1st_place_medal:

**Comment by JUL1EN094** [comment]
v1.1.4 available
