### ISSUE TITLE
No live TV  stream on FranceTV Pluzz addon since january 20th

### ISSUE THREAD

**Issue by sm1090** [JUL1EN094/JUL1EN094-xbmc-addons#20]
Dear Jul1en094,

Sorry to bother you again. It seems that there were changes in the live stream of France TV, as a result your addon stopped working for live stream on January 20th. Replay is however still possible with FranceTV addon.

In case you could do anything to get the live stream back, I would be very grateful.

Many thanks for providing this wonderful piece of software.

**Comment by JUL1EN094** [comment]
Please try last commit : 297c5ad

If you could gimme a feedback ?

**Comment by X-ardion** [comment]
Hi Jul1en094, just try it, the direct channels are working but no sound.  Tks

**Comment by sm1090** [comment]
Dear Jul1en094,

Thanks a lot for your quick answer.

I gave it a try and I had the following issues:
-- there is no sound on the live stream.
-- I am not sure it always works. Once the addon has been run once, it seems not to work any longer when I exit and start it again.

Is there anything else I could do to help you?

Thanks again for your work.

**Comment by JUL1EN094** [comment]
Hi, please could you tell me on witch system you are ? Android, ios,
windows...?

**Comment by sm1090** [comment]
Hi Jul1en094,

I use Openelec 7.0.1 (relying on Kodi 16.1) running on a Raspberry Pi 2+.

I tried again the addon today after I manually updated Kodi from 7.0.0 to 7.0.1 and I was not able to reproduce the problem when exiting the addon and running it again.

Unfortunately I could confirm the sound issue: there is no sound on any of the live streams (at least, those that I can access, I could not test any of the "1ère" oversea channels), whereas the replay works fine (with sound).

**Comment by JUL1EN094** [comment]
Ok thanks. Please try to replace 'video_ipad_v5' by 'video_ipad' in default.py... Hope sound will come back like that ??

**Comment by JUL1EN094** [comment]
v1.1.4 available

**Comment by sm1090** [comment]
Dear Jul1en094,
I'll give a try tonight (I could not do anything during the week-end).
Thanks again for your work.

**Comment by sm1090** [comment]
Indeed it seems to work fine (with the sound).
Great job!
Thank you again.
