### ISSUE TITLE
Support reglages de proxy de Kodi

### ISSUE THREAD

**Issue by camelreef** [JUL1EN094/JUL1EN094-xbmc-addons#21]
Bonjour,

Il me semble que cet Addon ne respecte pas les reglages de proxy de Kodi.

Mon cas est le suivant:
Je suis a Londres
J'ai un Raspberry Pi utilisant Kodi via la distribution LibreELEC.
Sur ce Pi, je demarre un proxy SOCKS5 via SSH sur un serveur localise en France.
Je regle Kodi pour utiliser ce proxy.
Je devrais pouvoir avoir acces au contenu reserve a la France via le proxy/tunnel, mais en fait je me fais toujours refuser l'acces.
Je pense donc que l'addon accede directement au net sans prendre en compte les reglages de Proxy de Kodi

Merci beaucoup pour l'addon, il me permet de rester en contact avec le pays malgre l'expatriation!

**Comment by camelreef** [comment]
PS: j'aurais vraiment aime regarder le live de la soiree des elections de France 2...

**Comment by camelreef** [comment]
Je suis utilisateur de plugin.video.FranceTVPluzz et freplay!

**Comment by camelreef** [comment]
Demonstration a la main, en utilisant cURL, que le proxy SOCKS5 marche bien:

```
Chambre:~/.kodi/temp # curl http://live.francetv.fr/simulcast/France_2/hls_v1/ZXhwPTE0OTI5ODQzMjR+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzX3YxKn5obWFjPWU1M
jMzM2I1NmUwOGMyYjJjZDRkMWI1YWJhNTdlMWExZWJmYTRkM2UzYjhmYWZlNDkyMmIyYzkzYTU5NDg2MzQ=/index.m3u8?hdnea=exp=1492963324~acl=%2fsimulcast%2fFrance_2%2fhls_v1*~hmac=
c50668a73cf696e92f78b26994cc8a01f341ed8d4c09efd50d91c0f58b0c6b3c
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;live&#46;francetv&#46;fr&#47;simulcast&#47;France&#95;2&#47;hls&#95;v1&#47;ZXhwPTE0OTI5ODQzMjR&#43;YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzX3YxKn5obWFjPWU1MjMzM2I1NmUwOGMyYjJjZDRkMWI1YWJhNTdlMWExZWJmYTRkM2UzYjhmYWZlNDkyMmIyYzkzYTU5NDg2MzQ&#61;&#47;index&#46;m3u8&#63;" on this server.<P>
Reference&#32;&#35;18&#46;47caffb0&#46;1492962957&#46;15feb538
</BODY>
</HTML>
```


```
Chambre:~/.kodi/temp # curl --proxy socks5h://localhost:8080 http://live.francetv.fr/simulcast/France_2/hls_v1/ZXhwPTE0OTI5ODQzMjR+YWNsPSUyZnNpbXVsY2FzdCUyZkZy
YW5jZV8yJTJmaGxzX3YxKn5obWFjPWU1MjMzM2I1NmUwOGMyYjJjZDRkMWI1YWJhNTdlMWExZWJmYTRkM2UzYjhmYWZlNDkyMmIyYzkzYTU5NDg2MzQ=/index.m3u8?hdnea=exp=1492963324~acl=%2fsim
ulcast%2fFrance_2%2fhls_v1*~hmac=c50668a73cf696e92f78b26994cc8a01f341ed8d4c09efd50d91c0f58b0c6b3c
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=231080,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=256x144
France_2-video=152400-audio_AACL_fra_65600_315=65600.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=362520,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=320x180
France_2-video=276400-audio_AACL_fra_65600_315=65600.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=656352,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=512x288
France_2-video=553600-audio_AACL_fra_65600_315=65600.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=933648,CODECS="avc1.77.31,mp4a.40.2",RESOLUTION=704x396
France_2-video=815200-audio_AACL_fra_65600_315=65600.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1622648,CODECS="avc1.77.31,mp4a.40.2",RESOLUTION=1024x576
France_2-video=1465200-audio_AACL_fra_65600_315=65600.m3u8
```

**Comment by spmjc** [comment]
Je n'ai rien fait de spécial sure foreplay or respecter où ne pas respecter
les règles de proxy.
Perso, j'habite à NYC. J'utilise unions, payant mais pas cher et fonctionne
très bien.
Tu as juste à changer le DNS sur t routeur.
Tu as une période d'essai je crois.
Ça pourrait résoudre les problèmes pour aujourd'hui..

**Comment by spmjc** [comment]
Désolé mon correcteur fait des siennes...
Je parlais de Freeplay:) et unodns.

**Comment by camelreef** [comment]
J’essaye d’éviter les solutions payantes (et douteuses niveau de ce qu’ils font avec les données), et j’ai une machine en France.

Il y aurait-il un moyen de verifier l’utilisation du réglage de proxy, quand meme, pour le long terme ?

Pas trop long la queue pour voter a NYC? Plus de 3h pour moi a Londres !

Nico

**Comment by spmjc** [comment]
C'était hier et..5 minutes..:)

**Comment by camelreef** [comment]
J’ai donc repris une demo de UnoTelly (Unodns), qui marche, en effet, et juste configure mon Kodi, pas le serveur DHCP pour toutes mes machine!

Il faudrait que je vois a monter un tel proxy (Unodns donne une resolution systématique sur leurs serveurs) chez moi, en fait…

Nico

**Comment by JUL1EN094** [comment]
Bonjour,

je clos l'issue qui n'a pas de lien avec l'addon a proprement parler. @camelreef, si tu as une machine en France, installer un serveur proxy dessus directement pourrais être une solution.

A+
