### ISSUE TITLE
FReplay : TMC ne fonctionne plus (besoin de se logger ?)

### ISSUE THREAD

**Issue by dbeniamine** [JUL1EN094/JUL1EN094-xbmc-addons#22]
Bonjour,

Depuis quelques jours, il n'est plus possible d'aller jusqu'à la liste des viéos d'une émission de TMC dans FReplay.

TMC force désormais à être connecté pour voir les vidéos, par exemple : https://www.tf1.fr/tmc/quotidien-avec-yann-barthes/videos/quotidien-premiere-partie-28-avril-2017.html

# Informations techniques

## Versions

    Kodi from Debian (16.1 Debian package version: 16.1+dfsg1-2~bpo8+1)
    FReplay 0.6.7 (installé depuis le repo Jul1EN094)

## Description du BUG

Quand je clique sur une émission (FReplay > TMC > Emission > Quotidien), j'ai l'erreur suivante :

    FReplay error
    
    check the log for more informaton

## Logs : 

    12:22:14 T:140181164226304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                Error Type: <type 'exceptions.AttributeError'>
                                                Error Contents: 'NoneType' object has no attribute 'getText'
                                                Traceback (most recent call last):
                                                  File "/home/kodi/.kodi/addons/plugin.video.freplay/default.py", line 149, in <module>
                                                    globalvar.channels[channel][1].list_videos(channel, param))
                                                  File "/home/kodi/.kodi/addons/plugin.video.freplay/resources/lib/channels/tf13.py", line 78, in list_videos
                                                    videoType = videoType.getText().encode('utf-8').lower()
                                                AttributeError: 'NoneType' object has no attribute 'getText'
                                                -->End of Python script error report<--
    12:22:14 T:140183324612800   ERROR: GetDirectory - Error getting plugin://plugin.video.freplay/?channel=tmc&mode=shows&name=Quotidien%20avec%20Yann%20Barth%c3%a8s&param=%2ftmc%2fquotidien-avec-yann-barthes
    12:22:14 T:140183324612800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.freplay/?channel=tmc&mode=shows&name=Quotidien%20avec%20Yann%20Barth%c3%a8s&param=%2ftmc%2fquotidien-avec-yann-barthes) failed

**Comment by spmjc** [comment]
La version de foreplay sur mon gite est à jour et les chaînes du groupe tf1
fonctionnent.

**Comment by dbeniamine** [comment]
Je viens de passer sur votre version, je confirme que ça fonctionne :)

**Comment by JUL1EN094** [comment]
Je clos l'issue. La MAJ 0.6.8 a été effectuée (https://github.com/JUL1EN094/JUL1EN094-xbmc-addons/tree/e28a5d7b1c9c749ceda71612ad9f5ab73b7ad5e3)
