### ISSUE TITLE
Coder d'autres addons

### ISSUE THREAD

**Issue by orion2036** [JUL1EN094/JUL1EN094-xbmc-addons#6]
Bonjour, désolé si ce n'est pas le bon endroit pour faire ce genre de demande mais je voulais savoir si vous pourriez coder des addons pour visionner les vidéos du site https://www.canal-u.tv/ et du site https://cnes.fr/fr 
Je n'ai malheureusement pas les compétences de codeur pour le faire moi même.
Merci au passage pour les autres addons que vous avez codé.

**Comment by spmjc** [comment]
Salut Orion2036,

Juli1en094 et moi travaillons sur un autre addon qui regroupe les replay de differentes chaines et sites web.
J'ai ajoute Canal U. Je n'ai pas bcp cherche mais n'ai pas trouve ou etaient les videos du site cnes.fr (si vous avez un lien..)
Vous pouvez trouver le forum de l'addon en question ici : 
http://media-passion.fr/add-ons-video/freplay-french-replay/

Voila.. :)

**Comment by orion2036** [comment]
Merci beaucoup :) je rêvais de pouvoir consulter ces vidéos depuis Kodi, 
je trouve que c'est une manière plus rapide de consulter des vidéos en 
HD de toute beauté, meme avec un nano pc de la taille d'un paquet de 
cigarette comme le Raspberry Pi 2 avec lequel j'ai découvert Kodi.
Les vidéos du CNES se trouvent à cette adresse : 
http://videotheque.cnes.fr/index.php
D'autres sites web meritent notre attention : 
http://videotheque.cnrs.fr/ http://www.universcience.tv/
Vous pourriez envisager de créer une partie éducatif et scientifique des 
addons avec ces sites web.
Merci pour le travail que vous réalisez :)

**Comment by JUL1EN094** [comment]
Bonjour à tous,

orion2036, je clos cette issue. J'ai reporté les informations sur cnes à l'adresse suivante, tu peux y mettre plus d'infos si tu as : 
https://github.com/spmjc/plugin.video.freplay/issues/46

Concernant CanalU, j'ai vu que tu avais déjà mis un retour (merci) ici, nous continuons donc à cet endroit  :
https://github.com/spmjc/plugin.video.freplay/issues/47

Si d'autres replay sont souhaités, créé une demande directement pour chaque chaîne directement ici : 
https://github.com/spmjc/plugin.video.freplay/issues

Merci.
