### ISSUE TITLE
Cannot fetch youtube trailer links anymore

### ISSUE THREAD

**Issue by NizarAloui** [JUL1EN094/JUL1EN094-xbmc-addons#7]
It is impossible since a while to extract youtube trailer links.

**Comment by JUL1EN094** [comment]
Hi,
Not sure to understand. 
Which module or addon are u talking about ?

**Comment by NizarAloui** [comment]
The module is script.module.getTrailer .
And precisely xgoogle.

**Comment by JUL1EN094** [comment]
I just pushed a fix.
Please could you check and tell me if it's better with this one (v0.0.3) ?

**Comment by NizarAloui** [comment]
Worked like a charm, thanks.

One other think, Youtube links are starting also with "https://" , so when getting result, we only have the "http://" links.

Thanks,

**Comment by JUL1EN094** [comment]
https://github.com/JUL1EN094/JUL1EN094-xbmc-addons/commit/0e4eb2e153a3c0a2f7b35a772bb05e539e38df69
